- name: ❌-no-repro
  description: Reproduction not provided
  color: FF0000
- name: ⌨️ accessibility
  description: Accessibility concerns
  color: FFA500
- name: 🤖 android
  description: Android platform
  color: 4BC74F
- name: ⚠️ breaking change
  description: Codebase changes
  color: FF0000
- name: 🐞 bug
  description: Application problem
  color: FFA500
- name: 🔧 build error
  description: Build issues
  color: 008672
- name: 🧹 cleanup
  description: Code cleanup or organization
  color: 008080
- name: 📦 dependencies
  description: Project dependencies
  color: FBCA04
- name: 🗑️ deprecated
  description: Deprecated features or code
  color: FF0000
- name: 📃 documentation
  description: Documentation updates
  color: C0C0C0
- name: 🖇 duplicate
  description: Duplicate issue
  color: FFEC27
- name: 🚀 enhancement
  description: Improvements
  color: 84B6EB
- name: ✨ feature
  description: New feature suggestion
  color: 00BFFF
- name: 📢 help wanted
  description: Assistance needed
  color: FF0000
- name: ❌ invalid
  description: Incomplete issue
  color: FFA500
- name: 🍏 ios
  description: iOS platform
  color: 3DDC84
- name: 🔨 maintenance
  description: Generic maintenance
  color: 00BFFF
- name: 🎈 performance
  description: Application performance
  color: 4682B4
- name: 💭 question
  description: Information request
  color: FF0000
- name: ⚛️ react native
  description: React Native development
  color: 007FFF
- name: ⚛️ react
  description: React development
  color: 007FFF
- name: 🔄 refactoring
  description: Code refactoring
  color: FF4500
- name: 🚨 security
  description: Security related issues
  color: 6A5ACD
- name: 💄 types
  description: TypeScript issues
  color: 00BFFF
- name: ❌ typo
  description: Typo is short for typographical error
  color: FFC0CB
- name: 🎨 UI/UX
  description: User interface or user experience
  color: 32CD32
- name: ⚠️ warning
  description: Application warnings
  color: FFEC27
- name: 🚧 WIP
  description: Work in progress
  color: FFD700
- name: ☠️ wontfix
  description: Acknowledged, won't be fixed
  color: 800080
