name: Build Example

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/build_example.yml'
      - 'android/**'
      - 'yarn.lock'

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk

      - name: Determine Yarn Cache Directory
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache node_modules
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./example

      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set Gradlew permissions
        run: chmod +x ./android/gradlew
        working-directory: ./example

      - name: Android Clean Cache
        run: yarn android:clean:cache
        working-directory: ./example

      - name: Gradlew Clean
        run: yarn android:clean
        working-directory: ./example

      - name: Gradlew Assemble Debug
        run: yarn android:assemble:debug
        working-directory: ./example
