name: Sync Labels

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/sync_labels.yml'
      - '.github/labels.yml'

permissions:
  pull-requests: write

jobs:
  sync:
    name: Sync Labels
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Syncs Labels
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
